### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by adryserage** [ReFlar/koseki#1]
`composer require reflar/koseki
`
```
  [InvalidArgumentException]
  Could not find a matching version of package reflar/koseki. Check the packa
  ge spelling, your version constraint and that the package is available in a
   stability which matches your minimum-stability (beta).
```

No more packagist ! :(
maybe its for the V0.8 of Flarum but juste put issue to lets you know !

**Comment by KyrneDev** [comment]
This extension is not released yet, please wait for the first version.

**Comment by adryserage** [comment]
aw damm sorry for disturbing ! add please Add `This extension is not released yet` to readme !

**Comment by Ralkage** [comment]
@KazeroG it clearly sates "[WIP]" in the description of the repo....added to the fact that it is not available on Packagist yet, a simple search there would tell you that this extension is unreleased.
