### ISSUE TITLE
Admin panel doesn't load when Koseki enabled

### ISSUE THREAD

**Issue by katosdev** [ReFlar/koseki#15]
When using **Reflar Koseki** on Beta8.1, once enabled head to /admin/ and users receive the error: **Unable to load the full version of this site. Try hard-refreshing this page to fix the error**
A hard refresh does not work, and returns the same error.

Had to remove using:
`composer remove reflar/koseki`

Steps to reproduce:
1. run: `composer require reflar/koseki`
2. Enable the extension in the ACP.
3. Close the tab, and navigate to main webpage. www.yourflarum.com
4. Go to user drop-down --> admin

![Error Message - ACP](https://user-images.githubusercontent.com/7927609/49823841-8ab7bc00-fd78-11e8-8dbc-90a647322f13.png)

**Comment by katosdev** [comment]
Speaking with @CDK2020 we believe this to be related to the **Tags** extension.
The following error is present in the console:

`Uncaught TypeError: Cannot read property 'prototype' of undefined
    at index.js:14
    at Application.js:127
    at Array.forEach (<anonymous>)
    at e.boot (Application.js:127)
    at admin:89`

**Comment by katosdev** [comment]
Output of app.initializers

```t {items: {…}}
items:
Reflar-Twofactor: r {content: ƒ, priority: 0, key: 13}
flagrow-upload: r {content: ƒ, priority: 0, key: 12}
flarum-approval: r {content: ƒ, priority: 0, key: 1}
flarum-flags: r {content: ƒ, priority: 0, key: 2}
flarum-likes: r {content: ƒ, priority: 0, key: 3}
flarum-statistics: r {content: ƒ, priority: 0, key: 8}
flarum-sticky: r {content: ƒ, priority: 0, key: 6}
flarum-tags: r {content: ƒ, priority: 0, key: 4}
lock: r {content: ƒ, priority: 0, key: 5}
reflar-koseki: r {content: ƒ, priority: -50, key: 10}
reflar/traditional-rank-icons: r {content: ƒ, priority: 0, key: 9}
reflar/webhooks: r {content: ƒ, priority: 0, key: 11}
suspend: r {content: ƒ, priority: 0, key: 7}
__proto__: Object
__proto__: Object```

**Comment by neoblizz** [comment]
Experiencing the same issue.
