### ISSUE TITLE
How to auto change color when switching to night mode?

### ISSUE THREAD

**Issue by sulf1ron** [ReFlar/koseki#3]
I've noticed two color style at the sample image page: https://imgur.com/a/ScNH2YA#7kRdwsG
I'm wondering if the latter image is night mode, and whether it is changed auto or mannually?
Thanks.

**Comment by KyrneDev** [comment]
This is our [nightmode extension](https://github.com/reflar/nightmode). You can also turn it on globally by using the "Dark mode" setting in our admin page.

**Comment by sulf1ron** [comment]
Maybe I found a bug..
For example, this is a tag map:
```
- Site Information
   - News
   - Moderation
   - Develop
- Test
(no subtags)
```
But on the user side (Koseki), it appears like this:
```
- Site Information (Strange color style)
   - News
   - Moderation
   - Develop
- Forum (a new primary tag whose color style is normal)
   - Test
```

**Comment by sulf1ron** [comment]
Screenshots are available here: https://imgur.com/a/wbrDiRV

**Comment by sulf1ron** [comment]
I found the first primary tag was colored by default, which is the reason why its color style is abnormal.
However, I've also found that if there's a primary tag without any sub tags, on Koseki it itself will become a sub tag belonging to a new primary tag called 'Forum'.

**Comment by Ralkage** [comment]
@sulf1ron please create a new issue if you believe you have found a bug.

**Comment by Shahiem** [comment]
The primary tag acts like a secondary tag when the  primary tag can't find a secondary tag (children). So it's not really a bug :)
