### ISSUE TITLE
Tag sidebar list is not visible after switching HomePage back to Tags or All Discussions

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/koseki#4]
I'm not sure if this was intended or not but as of 0.1.5, the sidebar will remain removed even when switching your `Home Page` settings back to `All Discussions` or `Tags`. The only way to restore the sidebar is to disable the extension altogether.

Any insight, @Shahiem?

I was prepared to use an issue template but we didn't add one to this repo yet.

**Comment by Shahiem** [comment]
Fixed in 1.0.7 (https://github.com/ReFlar/koseki/commit/9550963375cd8e7a7bd62df8b1586ae2a08b1660)
